"""CapCut export — EXPERIMENTAL.

Writes a CapCut desktop draft skeleton to
exports/<plan_id>_capcut/draft_content.json: canvas_config, materials_v2
(video entries with absolute paths + durations in microseconds) and a
timeline with one video track whose segments reference the materials with
source/target timeranges.

This is a template, not a pixel-perfect CapCut serialization — the schema
drifts between CapCut versions and is undocumented. Import it via CapCut's
"Import draft" and fix any material paths CapCut cannot resolve. A README.md
explaining this is written alongside the JSON. See API_CONTRACT.md
("experimental; doc-marked").
"""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from .. import config, models
from ..db import SessionLocal

log = logging.getLogger("mediaforge.capcut")

README = """# CapCut draft export (EXPERIMENTAL)

This folder is a best-effort CapCut desktop *draft_content.json* skeleton
generated by MediaForge (POST /api/export/capcut).

- It is a template: the CapCut draft schema is undocumented and changes
  between versions, so this may need manual repair after import.
- Material paths are absolute and point at your original media files; if
  CapCut cannot find them, re-link them inside CapCut.
- Timeline segments carry source/target timeranges in microseconds.

How to use: open CapCut desktop, use "Import" -> "Import draft" and select
this folder.
"""


def _load_plan(plan_id: str) -> list[tuple[models.EditClip, models.Asset]]:
    with SessionLocal() as db:
        plan = db.get(models.EditPlan, plan_id)
        if plan is None:
            raise ValueError(f"plan {plan_id!r} not found")
        rows = []
        for c in plan.clips:
            asset = db.get(models.Asset, c.asset_id)
            if asset is None:
                continue
            rows.append((c, asset))
        if not rows:
            raise ValueError(f"plan {plan_id!r} has no usable clips")
        return rows


def export_capcut(plan_id: str) -> str:
    """Write exports/<plan_id>_capcut/draft_content.json; returns its path."""
    rows = _load_plan(plan_id)
    out_dir = config.EXPORTS_DIR / f"{plan_id}_capcut"
    out_dir.mkdir(parents=True, exist_ok=True)

    materials: list[dict[str, Any]] = []
    segments: list[dict[str, Any]] = []
    target_cursor_us = 0  # microseconds
    for idx, (c, asset) in enumerate(rows, start=1):
        dur_s = max(0.1, float(c.end) - float(c.start))
        src_start_us = int(round(float(c.start) * 1_000_000))
        dur_us = int(round(dur_s * 1_000_000))
        mid = f"VID-{idx}"
        materials.append({
            "id": mid,
            "type": "video",
            "path": asset.path,
            "material_name": Path(asset.path).name,
            "duration": dur_us,
            "height": asset.height or 1080,
            "width": asset.width or 1920,
            "edit_ratio": (asset.height or 1080) / (asset.width or 1920),
        })
        segments.append({
            "id": f"SEG-{idx}",
            "material_id": mid,
            "target_timerange": {"start": target_cursor_us, "duration": dur_us},
            "source_timerange": {"start": src_start_us, "duration": dur_us},
            "transform": {
                "scale": {"x": 1.0, "y": 1.0},
                "rotation": 0.0,
                "position": {"x": 0.0, "y": 0.0},
            },
            "extra": {"caption": c.caption or ""},
        })
        target_cursor_us += dur_us

    ratio = "9:16"
    with SessionLocal() as db:
        plan = db.get(models.EditPlan, plan_id)
        if plan is not None and plan.target_ratio:
            ratio = plan.target_ratio

    draft: dict[str, Any] = {
        "version": 1,
        "name": f"MediaForge-{plan_id}",
        "canvas_config": {
            "width": 1080,
            "height": 1920 if ratio == "9:16" else 1080,
            "ratio": ratio,
        },
        "duration": target_cursor_us,
        "materials_v2": {"videos": materials, "audios": [], "texts": []},
        "timeline": {
            "tracks": [
                {
                    "type": "video",
                    "id": "TRACK-VIDEO-1",
                    "is_default_visible": True,
                    "segments": segments,
                }
            ]
        },
    }

    json_path = out_dir / "draft_content.json"
    json_path.write_text(
        json.dumps(draft, indent=2, ensure_ascii=False), encoding="utf-8")
    (out_dir / "README.md").write_text(README, encoding="utf-8")
    log.info("capcut draft written (experimental): %s (%d clips)",
             json_path, len(rows))
    return str(json_path)
